import React, { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import API from '../api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const DOMAINS = ['Software Engineer', 'Data Scientist', 'Web Developer', 'AI/ML Engineer', 'Cloud Engineer', 'Cybersecurity Analyst', 'Data Engineer'];

const LEVEL_CONFIG = {
  beginner: { color: '#06D6A0', icon: '🌱', label: 'Beginner' },
  intermediate: { color: '#FFD93D', icon: '🌿', label: 'Intermediate' },
  advanced: { color: '#FF6B6B', icon: '🌳', label: 'Advanced' },
};

// ── Beautiful PDF generator using jsPDF ──────────
function generateRoadmapPDF(domain, steps, done) {
  const doc = new jsPDF('p', 'pt', 'a4');
  
  // Header Background
  doc.setFillColor(124, 92, 252);
  doc.rect(0, 0, doc.internal.pageSize.width, 100, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('SMART CAREER GUIDANCE', 40, 45);
  
  // Subtitle
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`Learning Roadmap: ${domain}`, 40, 70);
  
  // Stats Date
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  const dateStr = `Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`;
  doc.text(dateStr, doc.internal.pageSize.width - 40, 45, { align: 'right' });
  
  const doneCount = done.length;
  doc.text(`Progress: ${doneCount} steps completed`, doc.internal.pageSize.width - 40, 70, { align: 'right' });

  let currentY = 130;

  const LEVELS = ['beginner', 'intermediate', 'advanced'];
  const colors = {
    beginner: [6, 214, 160],      // #06D6A0
    intermediate: [255, 217, 61], // #FFD93D
    advanced: [255, 107, 107]     // #FF6B6B
  };

  LEVELS.forEach(level => {
    const lvlSteps = steps[level] || [];
    if (!lvlSteps.length) return;

    doc.setFontSize(16);
    doc.setTextColor(...colors[level]);
    doc.setFont('helvetica', 'bold');
    doc.text(`${level.toUpperCase()} LEVEL`, 40, currentY);
    currentY += 15;

    const tableData = lvlSteps.map((stepObj, i) => {
      const title = stepObj.title || stepObj;
      const isDone = done.includes(title);
      return [
        isDone ? 'Yes' : 'No',
        i + 1,
        title,
        stepObj.url || 'N/A'
      ];
    });

    autoTable(doc, {
      startY: currentY,
      head: [['Done?', '#', 'Topic', 'Resource']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: colors[level],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      columnStyles: {
        0: { cellWidth: 40, halign: 'center' },
        1: { cellWidth: 30, halign: 'center' },
        2: { cellWidth: 250 },
        3: { cellWidth: 'auto' }
      },
      styles: {
        fontSize: 10,
        cellPadding: 5,
        valign: 'middle'
      },
      didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 0) {
          if (data.cell.raw === 'Yes') {
            data.cell.styles.textColor = [6, 214, 160];
            data.cell.styles.fontStyle = 'bold';
          } else {
            data.cell.styles.textColor = [150, 150, 150];
          }
        }
      }
    });

    currentY = doc.lastAutoTable.finalY + 30;
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Smart Career Guidance Platform', doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 30, { align: 'center' });

  doc.save(`${domain.replace(/ /g, '_')}_Roadmap.pdf`);
}

export default function Roadmap() {
  const [domain, setDomain] = useState('Software Engineer');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState([]);

  useEffect(() => {
    API.get('/roadmap/latest').then(r => setData(r.data)).catch(() => { });
    API.get('/progress/').then(r => setDone(r.data.completed_roadmap_steps || [])).catch(() => { });
  }, []);

  const generate = async () => {
    setLoading(true);
    try {
      const res = await API.post('/roadmap/generate', { career_domain: domain });
      setData(res.data);
      toast.success('Roadmap generated! 🗺️');
    } catch { toast.error('Failed to generate roadmap'); }
    finally { setLoading(false); }
  };

  const completeStep = async step => {
    try {
      await API.post('/roadmap/complete-step', { step });
      setDone(prev => [...prev, step]);
      toast.success('Step completed! 🎉');
    } catch { }
  };

  const totalSteps = data?.roadmap?.steps ? Object.values(data.roadmap.steps).flat().length : 0;
  const doneCount = done.length;
  const pct = totalSteps ? Math.round((doneCount / totalSteps) * 100) : 0;

  return (
    <div style={{ fontFamily: 'Inter,sans-serif' }}>
      <h1 className="page-title">Learning Roadmap</h1>
      <p className="page-sub">Personalized step-by-step career preparation plan</p>
      <div style={{ width: '100%' }}>
        {/* Generator */}
        <div className="card" style={{ marginBottom: 24, width: '100%', maxWidth: 800 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 }}>
            ⚙️ Generate Roadmap
          </div>
          <div style={{ display: 'flex', gap: 12 }}>
            <select value={domain} onChange={e => setDomain(e.target.value)} style={{ flex: 1 }}>
              {DOMAINS.map(d => <option key={d}>{d}</option>)}
            </select>
            <button className="btn btn-primary" onClick={generate} disabled={loading} style={{ flexShrink: 0 }}>
              {loading ? '⏳' : '🚀 Generate'}
            </button>
            {data?.roadmap?.steps && (
              <button className="btn btn-secondary" onClick={() => {
                generateRoadmapPDF(data.roadmap?.career_domain || domain, data.roadmap.steps, done);
                toast.success('Roadmap downloaded! 📥');
              }} style={{ flexShrink: 0 }}>
                📥 Download
              </button>
            )}
          </div>
        </div>

        {/* Progress header */}
        {totalSteps > 0 && (
          <div style={{
            marginBottom: 24, padding: '18px 24px', borderRadius: 18,
            background: 'linear-gradient(135deg,rgba(124,92,252,0.15),rgba(6,214,160,0.08))',
            border: '1px solid rgba(124,92,252,0.2)',
            display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap'
          }}>
            <div>
              <div style={{ fontFamily: 'Space Grotesk,sans-serif', fontSize: 32, fontWeight: 900, color: '#F0F0FF' }}>{pct}%</div>
              <div style={{ fontSize: 13, color: 'rgba(255,255,255,0.4)', fontWeight: 600 }}>{doneCount}/{totalSteps} steps done</div>
            </div>
            <div style={{ flex: 1, minWidth: 200 }}>
              <div style={{ height: 8, background: 'rgba(255,255,255,0.06)', borderRadius: 8 }}>
                <div style={{ height: '100%', borderRadius: 8, background: 'linear-gradient(90deg,#7C5CFC,#06D6A0)', width: `${pct}%`, transition: 'width 1s', boxShadow: '0 0 12px rgba(124,92,252,0.4)' }} />
              </div>
            </div>
          </div>
        )}

        {/* Skill gap */}
        {data?.skill_gap && (
          <div style={{
            marginBottom: 24, padding: 20, borderRadius: 18,
            background: 'rgba(255,107,107,0.06)', border: '1px solid rgba(255,107,107,0.15)'
          }}>
            <div style={{ fontWeight: 800, color: '#FF6B6B', fontSize: 15, marginBottom: 14 }}>
              📊 Skill Gap — {data.skill_gap.career_domain || domain}
            </div>
            <div style={{ display: 'flex', gap: 20, alignItems: 'center', marginBottom: 12, flexWrap: 'wrap' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 30, fontWeight: 900, color: '#FF6B6B' }}>{data.skill_gap.gap_percentage?.toFixed(1)}%</div>
                <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.4)' }}>Gap</div>
              </div>
              <div style={{ flex: 1, minWidth: 180 }}>
                <div style={{ height: 8, background: 'rgba(255,255,255,0.06)', borderRadius: 8 }}>
                  <div style={{ height: '100%', borderRadius: 8, background: '#06D6A0', width: `${100 - (data.skill_gap.gap_percentage || 0)}%`, transition: 'width 1s' }} />
                </div>
                <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.3)', marginTop: 4 }}>
                  {(100 - (data.skill_gap.gap_percentage || 0)).toFixed(1)}% matched
                </div>
              </div>
            </div>
            {data.skill_gap.missing_skills?.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {data.skill_gap.missing_skills.map(s => (
                  <span key={s} style={{ padding: '4px 12px', borderRadius: 20, background: 'rgba(255,107,107,0.12)', border: '1px solid rgba(255,107,107,0.25)', color: '#FF6B6B', fontSize: 12, fontWeight: 700 }}>{s}</span>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Steps by level */}
        {data?.roadmap?.steps && Object.entries(data.roadmap.steps).map(([level, steps]) => {
          const cfg = LEVEL_CONFIG[level] || { color: '#7C5CFC', icon: '📌', label: level };
          const levelDone = steps.filter(s => done.includes(s.title)).length;
          return (
            <div key={level} style={{ marginBottom: 28 }}>
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 14, flexWrap: 'wrap', gap: 8
              }}>
                <h2 style={{ fontFamily: 'Space Grotesk,sans-serif', fontWeight: 800, color: cfg.color, fontSize: 18 }}>
                  {cfg.icon} {cfg.label} Level
                </h2>
                <span style={{
                  padding: '4px 14px', borderRadius: 20,
                  background: `${cfg.color}18`, border: `1px solid ${cfg.color}33`,
                  color: cfg.color, fontSize: 13, fontWeight: 700
                }}>{levelDone}/{steps.length} done</span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 10, width: '100%' }}>
                {steps.map((stepObj, i) => {
                  const title = stepObj.title || stepObj; // handle backward compat
                  const url = stepObj.url;
                  const isDone = done.includes(title);
                  return (
                    <div key={i} style={{
                      display: 'flex', alignItems: 'center', gap: 14, padding: '14px 18px', borderRadius: 14,
                      background: isDone ? `${cfg.color}0A` : 'rgba(255,255,255,0.03)',
                      border: `1px solid ${isDone ? cfg.color + '33' : 'rgba(255,255,255,0.06)'}`,
                      transition: 'all 0.2s'
                    }}>
                      <div style={{
                        width: 30, height: 30, borderRadius: '50%', flexShrink: 0,
                        background: isDone ? cfg.color : 'rgba(255,255,255,0.06)',
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        color: isDone ? '#fff' : 'rgba(255,255,255,0.3)',
                        fontWeight: 800, fontSize: 13,
                        boxShadow: isDone ? `0 0 10px ${cfg.color}55` : 'none'
                      }}>
                        {isDone ? '✓' : i + 1}
                      </div>
                      <div style={{ flex: 1 }}>
                        <span style={{ fontSize: 14, fontWeight: 600, color: isDone ? 'rgba(255,255,255,0.4)' : 'rgba(255,255,255,0.8)', textDecoration: isDone ? 'line-through' : 'none', display: 'block' }}>
                          {title}
                        </span>
                        {url && !isDone && (
                          <a href={url} target="_blank" rel="noreferrer" style={{ fontSize: 12, color: cfg.color, textDecoration: 'none', fontWeight: 700, marginTop: 4, display: 'inline-block' }}>
                            🔗 View Resource
                          </a>
                        )}
                      </div>
                      {!isDone && (
                        <button onClick={() => completeStep(title)} style={{
                          padding: '6px 14px', borderRadius: 10, border: `1px solid ${cfg.color}44`,
                          background: `${cfg.color}12`, color: cfg.color,
                          fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'Inter,sans-serif',
                          flexShrink: 0, transition: 'all 0.2s'
                        }}
                          onMouseEnter={e => e.currentTarget.style.background = `${cfg.color}25`}
                          onMouseLeave={e => e.currentTarget.style.background = `${cfg.color}12`}
                        >Mark Done ✓</button>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}

        {!data && (
          <div style={{ textAlign: 'center', padding: 60 }}>
            <div style={{ fontSize: 60, marginBottom: 16 }}>🗺️</div>
            <h3 style={{ fontFamily: 'Space Grotesk,sans-serif', fontWeight: 800, fontSize: 20, color: 'rgba(255,255,255,0.6)', marginBottom: 8 }}>No roadmap yet</h3>
            <p style={{ color: 'rgba(255,255,255,0.3)', fontSize: 14 }}>Select a career domain and generate your personalized roadmap.</p>
          </div>
        )}
      </div>
    </div>
  );
}


